const sillas = [{
    name: 'Silla Escritorio',
    description: 'Silla de escritorio blanca de Aluminio',
    material: 'Aluminio y Cuerina',
    price_normal: 40000,

    discount: '12%',
    img: 'Muebles/Sillas/1.jpg',
    category: 'sillas'

}, {
    name: 'Silla Eco-Cuero',
    description: 'Silla de Living',
    material: 'Aluminio y Eco-Cuero',
    price_normal: 20000,
    discount: '12%',
    img: 'Muebles/Sillas/2.jpg',
    category: 'sillas'
},
{
    name: 'Silla Nordica negra',
    description: 'Silla Nordica ',
    material: 'Madera y Plastico',
    price_normal: 25000,
    discount: '12%',
    img: 'Muebles/Sillas/3.jpg',
    category: 'sillas'

},
{
    name: 'Silla Elegante Antigua',
    description: 'Silla gris de madera con chenille',
    material: 'Madera y Chenille',
    price_normal: 35000,
    discount: '12%',
    img: 'Muebles/Sillas/4.jpg',
    category: 'sillas'

},
{
    name: 'Silla Loca',
    description: 'Silla Loca de Cuero',
    material: 'Cuero y Madera',
    price_normal: 27000,
    discount: '12%',
    img: 'Muebles/Sillas/5.jpg',
    category: 'sillas'

},
{
    name: 'Silla Simil Madera',
    description: 'Silla de roble',
    material: 'Roble y Algodon',
    price_normal: 14000,
    discount: '12%',
    img: 'Muebles/Sillas/6.jpg',
    category: 'sillas'

},
]