/* 
{
    name: ,
    description: ,
    material: ,
    price_normal: 200000,
    discount: 12,
    img: ,
    category: 
}, */


export const stock = [{
    name: 'Silla Escritorio',
    description: 'Silla de escritorio blanca de Aluminio',
    material: 'Aluminio y Cuerina',
    price_normal: 40000,
    discount: '12',
    img: '././Muebles/Sillas/1.jpg',
    category: 'sillas',
    id: 1,

}, {
    name: 'Silla Eco-Cuero',
    description: 'Silla de Living',
    material: 'Aluminio y Eco-Cuero',
    price_normal: 20000,
    discount: '12',
    img: '././Muebles/Sillas/2.webp',
    category: 'sillas',
    id: 2

},
{
    name: 'Silla Nordica negra',
    description: 'Silla Nordica ',
    material: 'Madera y Plastico',
    price_normal: 25000,
    discount: '12',
    img: '././Muebles/Sillas/3.webp',
    category: 'sillas',
    id: 3

},
{
    name: 'Silla Elegante Antigua',
    description: 'Silla gris de madera con chenille',
    material: 'Madera y Chenille',
    price_normal: 35000,
    discount: '12',
    img: '././Muebles/Sillas/4.jpg',
    category: 'sillas',
    id: 4

},
{
    name: 'Silla Loca',
    description: 'Silla Loca de Cuero',
    material: 'Cuero y Madera',
    price_normal: 27000,
    discount: '15',
    img: './Muebles/Sillas/5.jpg',
    category: 'sillas',
    id: 5

},
{
    name: 'Silla Simil Madera',
    description: 'Silla de roble',
    material: 'Roble y Algodon',
    price_normal: 14000,
    discount: '15',
    img: './Muebles/Sillas/6.webp',
    category: 'sillas',
    id: 6

},


{
    name: 'Sommier Piero 2 plazas',
    description: 'Sommier 2 plazas base Madera',
    material: 'Colchon resortes y base de madera',
    price_normal: 90000,
    discount: 10,
    img: './Muebles/Sommiers/1.jpg',
    category: 'sommiers',
    id: 1

}, {
    name: 'Cama Premium ',
    description: 'Cama Premium Base Aluminio Colchon resort',
    material: 'Base Aluminio Colchon Resortes Resort',
    price_normal: 120000,
    discount: 10,
    img: './Muebles/Sommiers/2.jpg',
    category: 'sommiers',
    id: 2
}, {
    name: 'Cama Flotante',
    description: 'Cama son soporte de Pared Efecto Flotante',
    material: 'Colchon Evalastic Base Reforzada metal',
    price_normal: 150000,
    discount: 5,
    img: './Muebles/Sommiers/3.jpg',
    category: 'sommiers',
    id: 3
}, {
    name: 'Cama Futuristica',
    description: 'Cama Base con ovalada y Cholchon de Evalastic con Euro Pillow',
    material: 'Colchon Evalastic Algodon Euro Pillow',
    price_normal: 200000,
    discount: 12,
    img: './Muebles/Sommiers/4.jpg',
    category: 'sommiers',
    id: 4
},


{
    name: 'Set Mesa y Sillas Plasticos ',
    description: ' Mesa 1,8M X 0.7M y Sillas Plastico Negro con relieve ',
    material: 'Plastico de alta resistencia',
    price_normal: 120000,
    discount: 12,
    img: './Muebles/Exterior/1.jpg',
    category: 'exterior',
    id: 1,


}, {
    name: 'Set Mesa Sillas de Diseño',
    description: 'Sillas de Diseño y Mesa de Vidrio 1,8M X 0.7M',
    material: 'Madera y Vidrio',
    price_normal: 200000,
    discount: 12,
    img: './Muebles/Exterior/2.jpg',
    category: 'exterior',
    id: 2
}, {
    name: 'Set Mesa y Sillas Blancas Anti-Humedad',
    description: 'Set Blanco y Mesa Resistente 1,8M X 0.7M',
    material: 'Sillas y Mesa Plastica',
    price_normal: 80000,
    discount: 12,
    img: './Muebles/Exterior/3.jpg',
    category: 'exterior',
    id: 3
}, {
    name: 'Set de Diseño Metalico',
    description: 'set Moderno Metal ',
    material: 'Mesa 3M X 1M Sillas Madera y Metal ',
    price_normal: 250000,
    discount: 12,
    img: './Muebles/Exterior/4.jpg',
    category: 'exterior',
    id: 4
}, {
    name: 'Set Aluminio',
    description: 'Sillas Y Mesa Aluminio 2M x 0.8M',
    material: 'Aluminio',
    price_normal: 120000,
    discount: 12,
    img: './Muebles/Exterior/5.webp',
    category: 'exterior',
    id: 5
},

{
    name: 'Mesa Simil Madera ',
    description: 'Mesa extremos de Aluminio Centro Madera Patas Aluminio 1.8M X 0.8M',
    material: 'Madera y Aluminio',
    price_normal: 100000,
    discount: 12,
    img: './Muebles/Mesas/1.jpg',
    category: 'mesas',
    id: 1

}, {
    name: 'Mesa Redonda Vidrio',
    description: 'MESA EAMES REDONDA DE VIDRIO PATAS DE MADERA 120 CM',
    material: 'Vidrio Patas de Madera',
    price_normal: 70000,
    discount: 12,
    img: './Muebles/Mesas/2.jpg',
    category: 'mesas',
    id: 2
}, {
    name: 'Mesa de Madera Roble',
    description: 'Mesa grande Madera extra Fuerte Roble 2M X 0.9M',
    material: 'Roble',
    price_normal: 200000,
    discount: 12,
    img: './Muebles/Mesas/3.webp',
    category: 'mesas',
    id: 3
}, {
    name: 'Mesa Bambu Liviana',
    description: ' Mesa De Bambu Ultra Liviana 2M X 1M',
    material: 'Bambu',
    price_normal: 13000,
    discount: 12,
    img: './Muebles/Mesas/4.jpg',
    category: 'mesas',
    id: 4
}, {
    name: 'Mesa de Diseño Premium ',
    description: 'Mesa Premiun Acabados Artisticos',
    material: 'Madera de Arce Y Metal',
    price_normal: 300000,
    discount: 12,
    img: './Muebles/Mesas/5.jpg',
    category: 'mesas',
    id: 5
},

{
    name: 'Ropero Suix Melamina',
    description: 'Ropero 2M X 2,5M',
    material: 'Melamina',
    price_normal: 50000,
    discount: 12,
    img: './Muebles/Roperos/1.jpg',
    category: 'roperos',
    id: 1

}, {
    name: 'Ropero Madera Abedul',
    description: 'Ropero Clasico Con Madera De Abedul Color Natural',
    material: 'Abedul',
    price_normal: 30000,
    discount: 12,
    img: './Muebles/Roperos/2.jpg',
    category: 'roperos',
    id: 2
}, {
    name: 'Ropero Clasico Gris',
    description: 'Ropero Melamina Gris Ceniza',
    material: 'Melamina',
    price_normal: 33000,
    discount: 12,
    img: './Muebles/Roperos/3.jpg',
    category: 'roperos',
    id: 3
}, {
    name: 'Ropero Naranja con Barniz',
    description: 'Ropero Madera Barnizada',
    material: 'Madera Roble',
    price_normal: 60000,
    discount: 12,
    img: './Muebles/Roperos/4.webp',
    category: 'roperos',
    id: 4
}, {
    name: 'Ropero Bi Color',
    description: 'Ropero gis caoba y marron oscuro 2M X 1M',
    material: 'Melamina',
    price_normal: 70000,
    discount: 12,
    img: './Muebles/Roperos/5.jpg',
    category: 'roperos',
    id: 5
},

{
    name: 'Sofa Gris',
    description: 'Sofa 2 cuerpo Gris  2M X 0.7M',
    material: 'Madera y Chenille',
    price_normal: 130000,
    discount: 12,
    img: './Muebles/Sofas/1.jpg',
    category: 'sofas',
    id: 1

},
{
    name: 'Sofa cama gris',
    description: 'Sofa rebatible en cama 2M X 1.5M',
    material: 'Chenille',
    price_normal: 150000,
    discount: 12,
    img: './Muebles/Sofas/2.jpg',
    category: 'sofas',
    id: 2,
},
{
    name: 'Sofa Premium Montevideo',
    description: 'Sofa 3 Cuerpos Premiun Blanco Importado 2.5M X 1M',
    material: 'Chenille Importado',
    price_normal: 250000,
    discount: 12,
    img: './Muebles/Sofas/4.jpg',
    category: 'sofas',
    id: 3
},
{
    name: 'Sofa XL 3 Ceniza',
    description: 'Soga blanco amplio XL 2,2M X 1,7M',
    material: 'Tela ',
    price_normal: 100000,
    discount: 12,
    img: './Muebles/Sofas/3.jpg',
    category: 'sofas',
    id: 4
},
{
    name: 'Sofa Paris Total Black',
    description: 'Sofa Negro Soporte ultra resistentes',
    material: 'Chenille',
    price_normal: 220000,
    discount: 12,
    img: './Muebles/Sofas/5.jpg',
    category: 'sofas',
    id: 5
}]